package world.willfrog.agentlangchain.failure;

public enum LangchainFailureCategory {
    BUDGET_EXCEEDED,
    TOOL_ERROR,
    REPEATED_TOOL_CALL,
    PARAM_RETRY_WITH_HINT,
    INFRA_RETRY,
    EMPTY_OUTPUT,
    UNKNOWN,

    // Provider/模型错误细分（Phase 3.1）
    PROVIDER_TRANSIENT,
    PROVIDER_RATE_LIMIT,
    PROVIDER_BAD_REQUEST,
    PROVIDER_MODEL_UNAVAILABLE,
    PROVIDER_AUTH_REJECTED,
    PROVIDER_UNKNOWN,

    // Budget 维度细分（Phase 3.1）
    BUDGET_EXCEEDED_LLM_CALLS,
    BUDGET_EXCEEDED_TOKENS,
    BUDGET_EXCEEDED_TOOL_CALLS,
    BUDGET_EXCEEDED_WALL_CLOCK,
    BUDGET_EXCEEDED_HTTP_ATTEMPTS
}
